
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test_mybatis?serverTimezone=GMT&characterEncoding=utf-8
#    username: root
#    password: 1111
#  jdbc:
#    template:
#      query-timeout: 3 # /s

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_mybatis?serverTimezone=GMT&characterEncoding=utf-8
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: com.atguigu.admin.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet:   # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter:  # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat:    # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

#spring:
#  mvc:
#    static-path-pattern: /res/**   这个会导致welcome page功能、Favicon 功能失效
#  resources:
#    static-locations: [classpath:/haha/]





# Person
person:
  userName: lisi
  #userName: 'lisi \n' -> "lisi \\n"   "lisi \n" -> "lisi \n" 输出换行
  #单引号原样输出 会转义	\\n
  #双引号会解释特殊字符 不会转义 \n
  boss: true
  birth: 2020/8/18
  age: 20
  #行内写法 interests: [basketball,football]
  interests:
    - basketball
    - football
  animal: [cat,dog]
  #行内写法 score: {math:100,english:99} JSON写法可以不用空格
  score:
    math: 100
    english: 99
  salarys:
    - 234.2
    - 2999.0
  pet:
    name: tom
    weight: 18.9
  allPets:
    sick:
      - { name: tom }
      - { name: jerry,weight: 47 }
    health:
      - { name: mario,weight: 47 }