spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_mybatis?serverTimezone=GMT&characterEncoding=utf-8
    username: root
    password: 1111
  jdbc:
    template:
      query-timeout: 3 # /s
